name: ffs_custom_loader
description: The "ffs_custom_loader" package is a Flutter library that provides custom and visually appealing loading components for mobile applications. It empowers developers to create loading animations that are unique and tailored to their application's style, thereby enhancing user engagement during loading phases.
version: 0.0.5
homepage: https://github.com/cesairekent/ffs_custom_loader

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.minititan.ffs_custom_loader
        pluginClass: custom_loader
      ios:
        pluginClass: custom_loader
      linux:
        pluginClass: custom_loader
      macos:
        pluginClass: custom_loader
      web:
        pluginClass: custom_loader
      windows:
        pluginClass: custom_loader
